# Generated by Django 5.1.1 on 2024-10-07 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0003_alter_brand_parent_alter_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PartnerStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='partner.partner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='catalogue.product')),
            ],
        ),
    ]
